sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          input_type: text
          display: 'Site Name'
          type: text
          listable: hidden
          validate:
            - required
      -
        handle: substrap
        field:
          input_type: text
          display: Substrap
          type: text
          listable: hidden
  variables:
    display: Variables
    fields:
      -
        handle: entries_per_page
        field:
          display: 'Entries Per Page'
          type: integer
          instructions: 'The default pagination limit for mounted collections'
          listable: hidden
          validate:
            - required
